### ISSUE TITLE
failed to load command: unicorn

### ISSUE THREAD

**Issue by Shellfishgene** [anzaika/selectoscope#1]
Hi!

Just tried to use selectoscope and followed the install commands (on Ubuntu 16.04). Seems to have worked ok, except I have to use the docker-compose commands with sudo.
However after starting the server I can't connect, I assume the following is the relevant error:
```
web_1      | bundler: failed to load command: unicorn (/usr/local/bin/unicorn)
web_1      | ArgumentError: directory for stderr_path=/opt/app/log/unicorn.log not writable
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:88:in `block in reload'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:84:in `each'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:84:in `reload'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:65:in `initialize'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `new'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `initialize'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `new'
web_1      |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
web_1      |   /usr/local/bin/unicorn:23:in `load'
web_1      |   /usr/local/bin/unicorn:23:in `<top (required)>'
selectoscope_web_1 exited with code 1
```

**Comment by anzaika** [comment]
Hi!

We're currently in the middle of a huge rewrite which will be bringing lots of new features and also will fix this error. We plan to release it around the middle of February.

I will keep this issue open until the new version is released. Thank you for your interest in our software!

**Comment by Shellfishgene** [comment]
Sounds great, I'll check back later then! Support for PRANK in codon mode and HyPhy would be great ;)

**Comment by rupesh-sinha** [comment]
Landed in the same problem while running "docker-compose -f compose_development.yml up"
web_1_273ed4e51e09 | bundler: failed to load command: unicorn (/usr/local/bin/unicorn)
web_1_273ed4e51e09 | ArgumentError: directory for stderr_path=/opt/app/log/unicorn.log not writable
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:88:in `block in reload'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:84:in `each'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:84:in `reload'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:65:in `initialize'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `new'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `initialize'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `new'
web_1_273ed4e51e09 |   /usr/local/lib/ruby/gems/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
web_1_273ed4e51e09 |   /usr/local/bin/unicorn:23:in `load'
web_1_273ed4e51e09 |   /usr/local/bin/unicorn:23:in `<top (required)>'
selectoscope_web_1_273ed4e51e09 exited with code 1


Any solution?

**Comment by idavydov** [comment]
As @anzaika didn't have a chance to reply, I'll step in.

Unfortunately, there was no development in selectoscope for a while. I do not expect that at any near future it will be working. At this point I would recommend using PAML or [godon](https://bitbucket.org/Davydov/godon/src/master/) for your analysis from the command-line.

Sorry about that.
